modifications in the build scripts

diff --git a/scripts/functions_build b/scripts/functions_build
--- a/scripts/functions_build
+++ b/scripts/functions_build
@@ -8,11 +8,61 @@
 
 set +u
 
+###====================
+# Make sure that the current working directory is in the PATH
+[[ ! :$PATH: == *:".":* ]] && export PATH="${PATH}:."
+
+# Get the directory where the script is located
+if [[ $(uname -s) == Darwin ]]; then
+  src_name="$( grealpath -s "${BASH_SOURCE[${#BASH_SOURCE[@]} - 1]}" )"
+  src_dir="$(cd "$(dirname "${src_name}" )" && pwd -P)"
+else
+  src_name="$( realpath -s "${BASH_SOURCE[${#BASH_SOURCE[@]} - 1]}" )"
+  src_dir="$(cd "$(dirname "${src_name}" )" && pwd -P)"
+fi
+
+lst="${src_dir:+${src_dir}/}functions_utilities ${src_dir:+${src_dir}/}scripts/functions_utilities functions_utilities"
+funcs=
+for ilst in ${lst}
+do
+  if [ -f "${ilst:-}" ]; then
+    funcs="${ilst}"
+    break
+  fi
+done
+
+if [ -n "${funcs:+1}" ]; then
+  source "${funcs}"
+
+  if [ $? -ne 0 ]; then
+    echo " ### ERROR :: in ${src_name}"
+    echo "     Cannot load the required file: ${funcs}"
+    echo "     Exiting now ..."
+    echo
+
+    unset src_name src_dir ilst funcs
+    return 1
+  fi
+else
+  echo " ### ERROR :: in ${src_name}"
+  echo "     Cannot load the required file: functions_utilities"
+  echo "     Exiting now ..."
+  echo
+
+  unset src_name src_dir ilst funcs
+  return 1
+fi
+
+unset src_name src_dir ilst funcs
+###====================
+
+
 MY_COMPILING_SYTEMS="gnu, intel, pgi"
 MY_COMPILING_PLATFORMS="custom, linux, cheyenne, gaea, hera, jet, orion, stampede, wcoss"
 
+
 ##################################################
-### MODELLING SYSTEM BUILD FUNCTIONS
+### BEG:: MODELLING SYSTEM BUILD FUNCTIONS
 ##################################################
 
 ###========================================
@@ -472,271 +522,6 @@ UsageTracs()
   exit 0
 }
 
-
-###========================================
-### checkFuncOpt()
-### Usage:      checkFuncOpt opt_name
-### Parameters:
-###   opt_name: The name of the option to a function
-###
-### Returns : Exits on error
-###
-### Exports : __OPTION_LIST
-###
-### Echoes  : NONE
-###
-### checkFuncOpt: Checks if an option to a function is already supplied.
-###========================================
-checkFuncOpt() {
-  local opt_inp opt_list
-
-  [ $# -eq 0 ] && return -1
-
-  opt_inp="$( strTrim "${1}" 2 )"
-  opt_inp="$( echo "${opt_inp}" | sed 's/^[-]*//' )"
-
-  opt_list="$( strTrim "${__OPTION_LIST}" 2 )"
-  [ -n ${opt_list:+1} ] && \
-    opt_list=":$( echo "${opt_list}" | sed 's/ /:/g' ):"
-
-  [ "$( echo "${opt_list}" | egrep -o ":${opt_inp}:" )" ] && return 1
-
-  __OPTION_LIST="${__OPTION_LIST} ${opt_inp}"
-  export __OPTION_LIST
-
-  return 0
-}
-
-###========================================
-### isInteger()
-### Usage:      isInteger var
-### Parameters: var
-### Returns:    1 if var is not an integer (0 is an integer as well)
-###             0 in any other case
-### Echoes:     NONE
-###========================================
-isInteger()
-{
-  local -i retval=1
-
-  [ $# -eq 0 ] && return ${retval}
-
-  if [ "${1:-UNDEF}" -eq "${1}" ] 2>/dev/null
-  then
-    retval=0
-  fi
-
-  return ${retval}
-}
-
-###========================================
-### getInteger()
-### Usage:      getInteger int
-### Parameters: int (int >=0 or, int < 0)
-### Returns:    1 if var is not an integer
-###             0 in any other case
-### Echoes:     int, if it is a valid integer (including 0),
-###             in any other case echoes an empty string
-###========================================
-getInteger()
-{
-  local -i retval=0
-  local echoval= minus=
-
-  # strip spaces, '+' signs and '-' signs
-  # if the first character of the string is '-', set the minus variable
-  echoval="$( echo "${1}" | sed 's/[[:space:]+]//g' )"
-  [ "X$( echo "${echoval:0:1}" )" = "X-" ] && minus="-"
-  echoval="${minus}$( echo "${echoval}" | sed 's/[[:space:]-]//g' )"
-
-  if isInteger ${echoval}; then
-    echoval="$(echo "scale=0; ${echoval} + 0" | bc -ql 2>/dev/null)"
-    retval=$?
-    echoval="${echoval:-0}"
-  else
-    echoval=
-    retval=1
-  fi
-
-  echo -n ${echoval}
-
-  return ${retval}
-}
-
-###========================================
-### getPosInteger()
-### Usage:      getPosInteger posint
-### Parameters: posint (posint >= 0)
-### Returns:    1 if var is not a positive integer
-###             0 in any other case
-### Echoes:     posint if it is a valid positive integer
-###             (including 0), in any other case echoes an
-###             empty string
-###========================================
-getPosInteger()
-{
-  local -i retval=0
-  local echoval=
-
-  echoval=$( getInteger "${1}" )
-  retval=$?
-
-  if [ ${retval} -ne 0 ] ; then
-    echoval=
-    retval=1
-  else
-    if [ ${echoval} -lt 0 ]; then
-      echoval=
-      retval=1
-    fi
-  fi
-
-  echo -n ${echoval}
-
-  return ${retval}
-}
-
-###========================================
-### getYesNo()
-### Usage:      getYesNo value
-### Parameters:
-###   value : The input value (the value of a parameter)
-###           The value of a bash parameter that is checked
-###           against TRUE/FALSE. If the value is one of:
-###             ">=1|y|yes|yea|yeah|yep"
-###           then the value of parameter is TRUE (answer = yes).
-###           If the value is one of:
-###             "<=0|n|no|not|nop|nope"
-###           then the value of parameter is FALSE (answer = no).
-###           If the value is empty then the value of parameter
-###           is FALSE (answer = no)
-###
-### Returns : NONE
-###
-### Exports : NONE
-###
-### Echoes  : A "yes" or "no" answer.
-###
-### getYesNo: Checks if a parameter is assigned a TRUE/FALSE value.
-###========================================
-getYesNo()
-{
-  local param answer
-  
-  param="$( echo "${1}" | tr '[:upper:]' '[:lower:]' )"
-
-  if [ "${param}" -eq "${param}" ] 2>/dev/null
-  then
-    [ ${param} -le 0 ] && param=0
-    [ ${param} -gt 0 ] && param=1
-  fi
-
-  case "${param}" in
-    1|y|yes|yea|yeah|yep) answer="yes" ;;
-     0|n|no|not|nop|nope) answer="no"  ;;
-                       *) answer=""    ;; # DEFAULT
-  esac
-
-  echo -n "${answer}"
-}
-
-###========================================
-### toUPPER()
-### Usage:      toUPPER string
-### Parameters:
-###   string : The string in to convert
-###
-### Returns : NONE
-###
-### Exports : NONE
-###
-### Echoes  : The input string converted to an all upper case string
-###
-### toUPPER: Converts a string to an all upper case string
-###========================================
-function toUPPER()
-{
-  echo "${1}" | tr '[:lower:]' '[:upper:]'
-}
-
-###========================================
-### toLOWER()
-### Usage:      toLOWER string
-### Parameters:
-###   string : The string in to convert
-###
-### Returns : NONE
-###
-### Exports : NONE
-###
-### Echoes  : The input string converted to an all lower case string
-###
-### toLOWER: Converts a string to an all lower case string
-###========================================
-function toLOWER()
-{
-  echo "${1}" | tr '[:upper:]' '[:lower:]'
-}
-
-###========================================
-### strESC()
-### Usage:      strESC string
-### Parameters:
-###   string : The input string
-###            The input string on which this function is applied
-###            to escape special characters used in bash/sed ...
-###
-### Returns : NONE
-###
-### Exports : NONE
-###
-### Echoes  : The modified string with its special characters escaped
-###
-### strESC: Escapes special characters in a string: "'()/[]*.
-###========================================
-strESC()
-{
-  echo -n "$( echo "${*}" | sed -e "s/[\"\'\(\)\/\*\!]/\\\&/g;s/\[/\\\&/g;s/\]/\\\&/g" )"
-}
-
-strESC1()
-{
-  echo -n "$( echo "${*}" | sed -e "s/[\&\/\*\!]/\\\&/g;s/\[/\\\&/g;s/\]/\\\&/g" )"
-}
-
-###========================================
-### strTrim()
-### Usage:      strTrim s1 flag
-### Parameters:
-###     s1 : The input string
-###   flag : Integer
-###          A value that controls the action of strTrim.
-###          If flag is zero or not present, trailing blanks are removed.
-###          Leading blanks are removed if it is equal to 1.
-###          Both are removed if it is equal to 2.
-###          In any other case, trailing blanks are removed.
-###
-### Returns : NONE
-###
-### Exports : NONE
-###
-### Echoes  : s1 with all leading and/or trailing
-###           white spaces removed.
-###
-### strTrim: Removes all leading and/or trailing white spaces
-###          from the input string
-###========================================
-function strTrim ()
-{
-  local trimFLG="${2:-0}"
-  local out_str=
-
-  case ${trimFLG} in
-    0) out_str="$(echo "${1}" | sed 's/[[:space:]]*$//')" ;;
-    1) out_str="$(echo "${1}" | sed 's/^[[:space:]]*//')" ;;
-    2) out_str="$(echo "${1}" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')" ;;
-    *) out_str="$(echo "${1}" | sed 's/[[:space:]]*$//')" ;;
-  esac
-
-  echo -n ${out_str}
-}
+##################################################
+### END:: MODELLING SYSTEM BUILD FUNCTIONS
+##################################################
