added ability to disable interactivity in the build scripts

diff --git a/scripts/functions_build b/scripts/functions_build
--- a/scripts/functions_build
+++ b/scripts/functions_build
@@ -84,13 +84,14 @@ ParseArgs()
   local ans0 ans ival intN
   local all_evars
 
-  all_evars="MY_CLEAN MY_ADD_CMAKE_FLAGS MY_COMPILER
+  all_evars="MY_ACCEPT_ALL MY_CLEAN MY_ADD_CMAKE_FLAGS MY_COMPILER
              MY_PARALLEL MY_PARMAKE MY_PLATFORM MY_INSTALL_DIR
              MY_PROJECT_DIR MY_TYPE MY_VERBOSE"
 
   for ival in ${all_evars}; do unset __${ival}; done
 
 
+  __MY_ACCEPT_ALL=0
   __MY_CLEAN=0
   __MY_ADD_CMAKE_FLAGS=
   __MY_COMPILER=
@@ -105,7 +106,7 @@ ParseArgs()
 
   # -----
   # Process the function options
-  opt_all=( c clean cmake_flags comp j par parallel plat platform prefix proj t type v verbose
+  opt_all=( accept_all c clean cmake_flags comp j par parallel plat platform prefix proj t type v verbose
             h help )
   opt_all=":$( echo "${opt_all[@]/#/-} ${opt_all[@]/#/--}" | sed 's/ /:/g' ):"
 
@@ -238,6 +239,22 @@ ParseArgs()
             __MY_VERBOSE="$( getMakeVerbosity "${__MY_VERBOSE}" )"
           fi
         ;;
+      -y | --y | -yes | --yes )
+          checkFuncOpt "--yes"
+          if [ $? -eq 0 ]; then
+            __MY_ACCEPT_ALL=1
+            if [ "X${opt_arg}" != "X" ]; then
+              if `isInteger "${opt_arg}"` ; then
+                __MY_ACCEPT_ALL=$( echo "${opt_arg}" )
+                [ ${opt_arg} -le 0 ] && __MY_ACCEPT_ALL=0
+                [ ${opt_arg} -ge 1 ] && __MY_ACCEPT_ALL=1
+              else
+                __MY_ACCEPT_ALL=0
+                [ "$( getYesNo "${opt_arg}" )" = "yes" ] && __MY_ACCEPT_ALL=1
+              fi
+            fi
+          fi
+        ;;
       -h | -help | --h | --help )
           UsageBuild ${nm_func}
         ;;
@@ -295,6 +312,11 @@ UsageBuild()
 
   echo "  -h|-help|--h|--help"
   echo "    Show this help screen."
+  echo
+  #---
+  echo "  -y|-yes|--y|--yes"
+  echo "    Automatically answer yes for all questions."
+  echo "    Default: 0|no (user is required to enter a yes/no response)."
   echo
   #---
   echo "  -c|--c|-clean|--clean [=|space] \"0|1|2|-3|-2|-1|yes|no\" (OPTIONAL)."
@@ -445,7 +467,7 @@ ParseArgsTracs()
             fi
           fi
         ;;
-      -y | --y | -year | --year )
+      -yr | --yr | -year | --year )
           checkFuncOpt "--year"
           if [ "X${opt_arg}" != "X" ]; then
             __MY_YEAR=$( getPosInteger "${opt_arg}" )
@@ -508,7 +530,7 @@ UsageTracs()
   echo "    Default: none."
   echo
   #---
-  echo "  -y|--y|-year|--year [=|space] \"year_of_storm\"."
+  echo "  -yr|--yr|-year|--year [=|space] \"year_of_storm\"."
   echo "    The year the storm happened."
   echo "    Default: none."
   echo
